import hashlib
import io
import os
import re
import sys
import zipfile

import requests

# --- Configuration ---
SENSITIVE_KEYWORDS = [
    "token",
    "password",
    "secret",
    "key =",
    "auth",
    "api_key",
    "credentials",
]
ERROR_PATTERNS = [
    r"Traceback \(most recent call last\):",
    r"ERROR:",
    r"Exception:",
    r"ImportError:",
    r"AttributeError:",
    r"TypeError:",
    r"ValueError:",
    r"FAILED",
    r"Error:",
    r"process exited with code",
]
MAX_LOG_LINES = 100
MAX_BODY_CHARS = 60000


def filter_sensitive(line):
    """Filter sensitive keywords from a log line."""
    line_lower = line.lower()
    for kw in SENSITIVE_KEYWORDS:
        if kw in line_lower:
            return "[FILTERED SENSITIVE LINE]"
    return line


def extract_errors_from_log(content):
    """Extract error lines from log content."""
    lines = content.splitlines()
    error_lines = []
    capture = False

    for line in lines:
        is_error_start = any(re.search(p, line) for p in ERROR_PATTERNS)
        if is_error_start:
            capture = True

        if capture:
            filtered = filter_sensitive(line)
            error_lines.append(filtered)
            if len(error_lines) >= MAX_LOG_LINES:
                break

    return "\n".join(error_lines)


def main():
    """Summarize CI logs and emit the result to stdout and the step summary."""
    token = os.environ.get("GITHUB_TOKEN")
    repo = os.environ.get("REPO")
    run_id = os.environ.get("RUN_ID")
    workflow_name = os.environ.get("WORKFLOW_NAME", "Unknown Workflow")

    if not (token and repo and run_id):
        print("Missing GITHUB_TOKEN, REPO, or RUN_ID environment variables.")
        sys.exit(1)

    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github.v3+json",
    }

    # 1. Download logs
    logs_url = f"https://api.github.com/repos/{repo}/actions/runs/{run_id}/logs"
    resp = requests.get(logs_url, headers=headers)
    if resp.status_code != 200:
        print(f"Failed to download logs. Status: {resp.status_code}")
        sys.exit(0)

    # 2. Extract errors
    summary_text = ""
    with zipfile.ZipFile(io.BytesIO(resp.content)) as z:
        for filename in z.namelist():
            if len(summary_text) >= MAX_BODY_CHARS:
                break

            if filename.endswith(".txt") or filename.endswith(".log"):
                with z.open(filename) as f:
                    content = f.read().decode("utf-8", errors="ignore")
                    errors = extract_errors_from_log(content)
                    if errors:
                        entry = f"### File: {filename}\n\n```text\n{errors}\n```\n\n"
                        if len(summary_text) + len(entry) > MAX_BODY_CHARS:
                            summary_text += "\n**... [Logs Truncated] ...**\n"
                            break
                        summary_text += entry

    if not summary_text:
        summary_text = "No explicit error patterns found in logs. Check full logs for details."

    # 3. Generate fingerprint (SHA-256 of the error summary)
    # We strip numbers/paths to make the fingerprint more stable across runs
    fingerprint_base = re.sub(r"/home/[^/]+/", "/HOME/", summary_text)
    fingerprint_base = re.sub(r"0x[0-9a-f]+", "0xADDR", fingerprint_base)
    fingerprint_base = re.sub(r"\d+", "N", fingerprint_base)

    fingerprint = hashlib.sha256(fingerprint_base.encode("utf-8")).hexdigest()[:16]
    fingerprint_marker = f"<!-- trace-fingerprint: {fingerprint} -->"

    summary = (
        f"## Automated CI Failure Summary\n\n"
        f"- **Workflow:** `{workflow_name}`\n"
        f"- **Run URL:** https://github.com/{repo}/actions/runs/{run_id}\n"
        f"- **Fingerprint:** `{fingerprint}`\n\n"
        "### Extracted Error Logs:\n\n"
        f"{summary_text}\n\n"
        "---\n"
        f"{fingerprint_marker}\n"
        "*This summary was automatically generated by Antigravity CI Log Summarizer.*"
    )

    summary_path = os.environ.get("GITHUB_STEP_SUMMARY")
    if summary_path:
        with open(summary_path, "a", encoding="utf-8") as handle:
            handle.write(summary)
            handle.write("\n")

    print(summary)


if __name__ == "__main__":
    main()
