import io
import os
import re
import sys
import zipfile

import requests

# --- Configuration ---
SENSITIVE_KEYWORDS = [
    "token",
    "password",
    "secret",
    "key =",
    "auth",
    "api_key",
    "credentials",
]
ERROR_PATTERNS = [
    r"Traceback \(most recent call last\):",
    r"ERROR:",
    r"Exception:",
    r"ImportError:",
    r"AttributeError:",
    r"TypeError:",
    r"ValueError:",
    r"FAILED",
    r"Error:",
    r"process exited with code",
]
MAX_LOG_LINES = 300


def filter_sensitive(line):
    """Filter sensitive keywords from a log line."""
    line_lower = line.lower()
    for kw in SENSITIVE_KEYWORDS:
        if kw in line_lower:
            return "[FILTERED SENSITIVE LINE]"
    return line


def extract_errors_from_log(content):
    """Extract error lines from log content based on predefined patterns."""
    lines = content.splitlines()
    error_lines = []
    capture = False

    for line in lines:
        is_error_start = any(re.search(p, line) for p in ERROR_PATTERNS)
        if is_error_start:
            capture = True

        if capture:
            filtered = filter_sensitive(line)
            error_lines.append(filtered)
            if len(error_lines) >= MAX_LOG_LINES:
                break

    return "\n".join(error_lines)


def main():
    """Summarize CI logs and create a GitHub issue."""
    token = os.environ.get("GITHUB_TOKEN")
    repo = os.environ.get("REPO")
    run_id = os.environ.get("RUN_ID")

    if not (token and repo and run_id):
        print("Missing GITHUB_TOKEN, REPO, or RUN_ID environment variables.")
        sys.exit(1)

    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github.v3+json",
    }

    # 1. Check for existing issue to avoid duplicates
    issue_title = f"CI failure run {run_id} - automated summary"
    search_url = f"https://api.github.com/repos/{repo}/issues"
    params = {"state": "open", "labels": "ci-failure,automated"}

    resp = requests.get(search_url, headers=headers, params=params)
    resp.raise_for_status()
    issues = resp.json()
    for issue in issues:
        if issue_title in issue["title"]:
            print(f"Issue already exists: {issue['html_url']}. Skipping.")
            return

    # 2. Download logs
    logs_url = f"https://api.github.com/repos/{repo}/actions/runs/{run_id}/logs"
    resp = requests.get(logs_url, headers=headers)
    if resp.status_code != 200:
        print(f"Failed to download logs. Status: {resp.status_code}")
        # Sometimes logs are not immediately available
        sys.exit(0)

    # 3. Extract logs
    summary_text = ""
    with zipfile.ZipFile(io.BytesIO(resp.content)) as z:
        for filename in z.namelist():
            if filename.endswith(".txt") or filename.endswith(".log"):
                with z.open(filename) as f:
                    content = f.read().decode("utf-8", errors="ignore")
                    errors = extract_errors_from_log(content)
                    if errors:
                        summary_text += (
                            f"### File: {filename}\n\n```text\n{errors}\n```\n\n"
                        )

    if not summary_text:
        summary_text = "No explicit error patterns found in the logs."

    # 4. Create Issue
    issue_body = (
        f"## Automated CI Failure Summary for Run {run_id}\n\n"
        f"**Run URL:** https://github.com/{repo}/actions/runs/{run_id}\n\n"
        "### Extracted Error Logs:\n\n"
        f"{summary_text}\n\n"
        "---\n"
        "*This issue was automatically generated by Antigravity CI Log Summarizer.*"
    )

    payload = {
        "title": issue_title,
        "body": issue_body,
        "labels": ["ci-failure", "automated"],
    }

    resp = requests.post(
        f"https://api.github.com/repos/{repo}/issues", headers=headers, json=payload
    )
    if resp.status_code == 201:
        print(f"Issue created successfully: {resp.json()['html_url']}")
    else:
        print(f"Failed to create issue: {resp.text}")
        sys.exit(1)


if __name__ == "__main__":
    main()
