from __future__ import annotations

import typing
from typing import Any, Protocol

import numpy as np
import numpy.typing as npt
from astropy import units as u

if typing.TYPE_CHECKING:
    from typing import Protocol

    class TimeSeriesAttrs(Protocol):
        """Structural attributes shared by TimeSeries-like classes for type checking."""

        value: npt.NDArray[Any]
        times: Any
        t0: Any
        dt: u.Quantity | None
        sample_rate: Any
        span: Any
        unit: Any
        name: str | None
        channel: Any
        size: int
        dtype: np.dtype[Any]
        shape: tuple[int, ...]
        ndim: int
        epoch: Any
        channel_names: Any

        def __init__(self, *args: Any, **kwargs: Any) -> None: ...
        def __len__(self) -> int: ...
        def astype(self, *args: Any, **kwargs: Any) -> Any: ...
        def copy(self, *args: Any, **kwargs: Any) -> Any: ...
        def resample(self, *args: Any, **kwargs: Any) -> Any: ...
        def lowpass(self, *args: Any, **kwargs: Any) -> Any: ...
        def highpass(self, *args: Any, **kwargs: Any) -> Any: ...
        def bandpass(self, *args: Any, **kwargs: Any) -> Any: ...
        def bandstop(self, *args: Any, **kwargs: Any) -> Any: ...
        def interpolate(self, *args: Any, **kwargs: Any) -> Any: ...
        def fft(self, *args: Any, **kwargs: Any) -> Any: ...
        def rfft(self, *args: Any, **kwargs: Any) -> Any: ...
        def psd(self, *args: Any, **kwargs: Any) -> Any: ...
        def asd(self, *args: Any, **kwargs: Any) -> Any: ...
        def csd(self, *args: Any, **kwargs: Any) -> Any: ...
        def coherence(self, *args: Any, **kwargs: Any) -> Any: ...
        def spectrogram(self, *args: Any, **kwargs: Any) -> Any: ...
        def crop(self, *args: Any, **kwargs: Any) -> Any: ...
        def hilbert(self, *args: Any, **kwargs: Any) -> Any: ...
        def abs(self, *args: Any, **kwargs: Any) -> Any: ...
        def to(self, *args: Any, **kwargs: Any) -> Any: ...
        def _prepare_data_for_transform(
            self,
            data: Any | None = None,
            window: Any | None = None,
            detrend: bool = False,
        ) -> np.ndarray: ...
        def _check_regular(self, method_name: str | None = None) -> None: ...
        def override_unit(self, unit: Any) -> None: ...

else:

    class TimeSeriesAttrs:
        """Runtime fallback for TimeSeriesAttrs."""

        pass
